'use client';
import Image from 'next/image';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { Dict } from '@/i18n';

const steps = [
  { key: 's1', video: '/images/how-it-works-step-1.mp4', poster: '/images/how-it-works-step-1.webp', alt: 'altHowStep1', labels: [] },
  { key: 's2', video: '/images/how-it-works-step-2.mp4', poster: '/images/how-it-works-step-2.webp', alt: 'altHowStep2', labels: ['s2Example1', 's2Example2', 's2Example3'] },
  { key: 's3', video: '/images/how-it-works-step-3.mp4', poster: '/images/how-it-works-step-3.webp', alt: 'altHowStep3', labels: ['s3Example1', 's3Example2', 's3Example3'] },
] as const;

export default function HowItWorksClient({ t }: { t: Dict }) {
  const sectionRef = useRef<HTMLElement>(null);
  const videos = useRef<(HTMLVideoElement | null)[]>([]);
  const cards = useRef<(HTMLElement | null)[]>([]);
  const played = useRef(new Set<number>());
  const pending = useRef<number | null>(null);
  const [sourcesAttached, setSourcesAttached] = useState(false);
  const [active, setActive] = useState<number | null>(null);
  const [playing, setPlaying] = useState<number | null>(null);
  const [ended, setEnded] = useState<Set<number>>(new Set());
  const [finePointer, setFinePointer] = useState(false);
  const [autoplayAllowed, setAutoplayAllowed] = useState(true);
  const stop = useCallback((i: number, reset = true) => { const v = videos.current[i]; if (!v) return; v.pause(); if (reset) v.currentTime = 0; setPlaying(x => x === i ? null : x); setActive(x => x === i ? null : x); }, []);
  const stopOthers = useCallback((except: number) => { videos.current.forEach((v, i) => { if (v && i !== except) stop(i); }); }, [stop]);
  const play = useCallback((i: number, deliberate = false) => { const v = videos.current[i]; if (!v || (!autoplayAllowed && !deliberate)) return; stopOthers(i); setActive(i); v.play()?.then(() => setPlaying(i)).catch(() => stop(i)); }, [autoplayAllowed, stop, stopOthers]);
  useEffect(() => { const reduced = window.matchMedia('(prefers-reduced-motion: reduce)'); const pointer = window.matchMedia('(pointer: fine)'); const c = (navigator as Navigator & { connection?: { saveData?: boolean; effectiveType?: string } }).connection; setFinePointer(pointer.matches); setAutoplayAllowed(!reduced.matches && !c?.saveData && !/(^|-)2g$/.test(c?.effectiveType ?? '')); const onMedia = () => { setFinePointer(pointer.matches); if (reduced.matches) setAutoplayAllowed(false); }; pointer.addEventListener?.('change', onMedia); reduced.addEventListener?.('change', onMedia); return () => { pointer.removeEventListener?.('change', onMedia); reduced.removeEventListener?.('change', onMedia); }; }, []);
  useEffect(() => { const section = sectionRef.current; if (!section || typeof IntersectionObserver === 'undefined') { setSourcesAttached(true); return; } const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setSourcesAttached(true); o.disconnect(); } }, { rootMargin: '240px 0px' }); o.observe(section); return () => o.disconnect(); }, []);
  useEffect(() => { if (pending.current !== null && sourcesAttached) { const i = pending.current; pending.current = null; requestAnimationFrame(() => play(i, true)); } }, [play, sourcesAttached]);
  useEffect(() => { if (finePointer || typeof IntersectionObserver === 'undefined') return; const o = new IntersectionObserver(() => { const centre = window.innerHeight / 2; const eligible = cards.current.map((card, i) => { if (!card) return null; const r = card.getBoundingClientRect(); const visible = Math.min(r.bottom, window.innerHeight) - Math.max(r.top, 0); return visible / Math.max(r.height, 1) >= .6 ? { i, d: Math.abs(r.top + r.height / 2 - centre) } : null; }).filter(Boolean) as { i: number; d: number }[]; const selected = eligible.sort((a, b) => a.d - b.d)[0]?.i; cards.current.forEach((_, i) => { if (selected !== i) stop(i); }); if (selected !== undefined && !played.current.has(selected)) { played.current.add(selected); play(selected); } }, { threshold: [0, .6, 1] }); cards.current.forEach(c => c && o.observe(c)); return () => o.disconnect(); }, [finePointer, play, stop]);
  useEffect(() => { const onVisibility = () => { if (document.hidden) videos.current.forEach((_, i) => stop(i)); }; document.addEventListener('visibilitychange', onVisibility); return () => document.removeEventListener('visibilitychange', onVisibility); }, [stop]);
  const begin = (i: number, deliberate = false) => { if (!sourcesAttached) { pending.current = i; setSourcesAttached(true); return; } play(i, deliberate); };
  return <section ref={sectionRef} id="how" className="mx-auto max-w-6xl scroll-mt-24 px-5 pb-14 md:px-8">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-medium">{t.how}</h2><p className="mt-2 text-sm font-medium text-brand-primary">{t.howMeta}</p></div><a href="#tell" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-brand-primary px-6 py-3 text-base font-medium text-white transition-opacity duration-150 hover:opacity-90 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-primary motion-reduce:transition-none">{t.cta1}</a></div>
    <p className="mt-7 text-xs font-medium uppercase tracking-[0.12em] text-brand-muted">{t.howIllustrative}</p>
    <div className="mt-4 grid gap-5 md:grid-cols-3">{steps.map((step, index) => { const heading = t[step.key + 't' as keyof Dict] as string; const description = t[step.key + 'ExampleDesc' as keyof Dict] as string; const reassurance = t[step.key + 'r' as keyof Dict] as string; const isActive = active === index; const label = playing === index ? t.howPause : ended.has(index) ? t.howReplay : t.howPlay; return <article key={step.key} ref={node => { cards.current[index] = node; }} className="flex min-w-0 flex-col rounded-2xl border border-brand-border bg-brand-story p-4 sm:p-5">
      <div className="mb-3 flex items-center gap-2.5"><span className="flex h-8 w-8 flex-none items-center justify-center rounded-full bg-brand-primary text-sm font-medium text-white">{index + 1}</span><h3 className="text-lg font-medium">{heading}</h3></div>
      <div className="relative aspect-[4/3] w-full overflow-hidden rounded-xl bg-brand-story" onMouseEnter={() => finePointer && begin(index)} onMouseLeave={() => finePointer && stop(index)}><Image src={step.poster} alt={t[step.alt as keyof Dict] as string} fill sizes="(min-width: 768px) 33vw, 100vw" className="object-cover" priority={index === 0} /><video ref={node => { videos.current[index] = node; }} src={sourcesAttached ? step.video : undefined} muted playsInline preload="none" aria-hidden="true" onEnded={() => { setPlaying(null); setEnded(current => new Set(current).add(index)); }} onError={() => stop(index)} className={"absolute inset-0 h-full w-full object-cover transition-opacity duration-150 motion-reduce:transition-none " + (isActive ? 'opacity-100' : 'opacity-0')} /><button type="button" onClick={() => { if (playing === index) stop(index, false); else { if (ended.has(index)) { setEnded(current => { const next = new Set(current); next.delete(index); return next; }); const v = videos.current[index]; if (v) v.currentTime = 0; } begin(index, true); } }} onFocus={() => autoplayAllowed && begin(index)} className="absolute bottom-3 right-3 min-h-11 rounded-full border border-white/70 bg-black/65 px-4 text-sm font-medium text-white transition-colors hover:bg-black/80 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white motion-reduce:transition-none" aria-label={label}>{label}</button></div>
      <div className="mt-4 space-y-2 text-sm leading-relaxed">{step.key === 's1' && <p className="rounded-xl border border-brand-border bg-white/70 px-3 py-2.5">“{t.s1ExampleSpeech}”</p>}{step.labels.map(labelKey => <p key={labelKey} className="flex items-center gap-2 px-1 py-1 text-sm"><span className="h-1.5 w-1.5 flex-none rounded-full bg-brand-primary" aria-hidden="true" />{t[labelKey as keyof Dict] as string}</p>)}<p className="pt-1 text-brand-muted">{description}</p></div><p className="mt-4 border-t border-dashed border-brand-border pt-3 text-xs leading-relaxed text-brand-muted">{reassurance}</p>
    </article>; })}</div><p className="mt-8 text-center text-sm font-medium text-brand-muted">{t.howClose}</p>
  </section>;
}
